source 'http://rubygems.org'

gem 'sequel', '3.42.0'

gem 'sinatra', '1.2.6'
gem 'rack', '1.3.3'
gem 'thin', '1.2.11'

gem 'slim', '1.2.0'
gem 'tilt', '1.3.3'
gem 'temple', '0.4.0'
gem 'redcarpet', '2.2.2'


group :development do
	gem 'sqlite3'
end

group :production do
	gem 'pg'
	gem 'mysql'
	gem 'sass', '3.1.7'
end
